# Generated by Django 5.1.3 on 2024-12-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mensajes', '0002_perfilavatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilAvatar',
        ),
    ]
